In [52]:
import pandas as pd
from rain_delay.preprocessing.flight_preprocessor import FlightPreprocessor
from rain_delay.data.flight_loader import FlightLoader
from rain_delay.data.dataset_builder import DatasetBuilder

In [2]:
df = pd.read_csv(
    "../data/raw/flights/2025/VRA_2025_01.csv",
    sep=";",
    encoding="utf-8"
)

In [3]:
df.head()

,Sigla ICAO Empresa Aérea,Empresa Aérea,Número Voo,Código DI,Código Tipo Linha,Modelo Equipamento,Número de Assentos,Sigla ICAO Aeroporto Origem,Descrição Aeroporto Origem,Partida Prevista,...,Sigla ICAO Aeroporto Destino,Descrição Aeroporto Destino,Chegada Prevista,Chegada Real,Situação Voo,Justificativa,Referência,Situação Partida,Situação Chegada,Codeshare
0,AAL,"AMERICAN AIRLINES, INC.",0904,0,I,B788,295,SBGL,AEROPORTO INTERNACIONAL DO RIO DE JANEIRO (GAL...,01/01/2025 23:55,...,KMIA,"MIAMI INTERNATIONAL AIRPORT - MIAMI, FLORIDA -...",02/01/2025 07:45,02/01/2025 08:11,REALIZADO,NaN,01/01/2025 00:00:00,Antecipado,Pontual,NaN
1,AAL,"AMERICAN AIRLINES, INC.",0905,0,I,B788,295,KMIA,"MIAMI INTERNATIONAL AIRPORT - MIAMI, FLORIDA -...",01/01/2025 01:10,...,SBGL,AEROPORTO INTERNACIONAL DO RIO DE JANEIRO (GAL...,01/01/2025 09:25,01/01/2025 09:24,REALIZADO,NaN,01/01/2025 00:00:00,Pontual,Antecipado,NaN
2,AAL,"AMERICAN AIRLINES, INC.",0906,0,I,B77W,318,SBGR,GUARULHOS - GOVERNADOR ANDRÉ FRANCO MONTORO - ...,01/01/2025 00:30,...,KMIA,"MIAMI INTERNATIONAL AIRPORT - MIAMI, FLORIDA -...",01/01/2025 08:55,01/01/2025 08:31,REALIZADO,NaN,01/01/2025 00:00:00,Antecipado,Antecipado,NaN
3,AAL,"AMERICAN AIRLINES, INC.",0925,0,I,B772,288,KMIA,"MIAMI INTERNATIONAL AIRPORT - MIAMI, FLORIDA -...",01/01/2025 23:50,...,SBGR,GUARULHOS - GOVERNADOR ANDRÉ FRANCO MONTORO - ...,02/01/2025 08:10,02/01/2025 08:37,REALIZADO,NaN,01/01/2025 00:00:00,Pontual,Pontual,NaN
4,AAL,"AMERICAN AIRLINES, INC.",0929,0,I,B77W,318,KMIA,"MIAMI INTERNATIONAL AIRPORT - MIAMI, FLORIDA -...",01/01/2025 20:50,...,SBGR,GUARULHOS - GOVERNADOR ANDRÉ FRANCO MONTORO - ...,02/01/2025 06:20,02/01/2025 06:44,REALIZADO,NaN,01/01/2025 00:00:00,Atraso 60-120,Pontual,NaN

In [4]:
df.shape

(89616, 21)

In [5]:
df.columns.tolist()

['Sigla ICAO Empresa Aérea',
 'Empresa Aérea',
 'Número Voo',
 'Código DI',
 'Código Tipo Linha',
 'Modelo Equipamento',
 'Número de Assentos',
 'Sigla ICAO Aeroporto Origem',
 'Descrição Aeroporto Origem',
 'Partida Prevista',
 'Partida Real',
 'Sigla ICAO Aeroporto Destino',
 'Descrição Aeroporto Destino',
 'Chegada Prevista',
 'Chegada Real',
 'Situação Voo',
 'Justificativa',
 'Referência',
 'Situação Partida',
 'Situação Chegada',
 'Codeshare']

In [6]:
df.dtypes

Sigla ICAO Empresa Aérea            str
Empresa Aérea                       str
Número Voo                          str
Código DI                           str
Código Tipo Linha                   str
Modelo Equipamento                  str
Número de Assentos                int64
Sigla ICAO Aeroporto Origem         str
Descrição Aeroporto Origem          str
Partida Prevista                    str
Partida Real                        str
Sigla ICAO Aeroporto Destino        str
Descrição Aeroporto Destino         str
Chegada Prevista                    str
Chegada Real                        str
Situação Voo                        str
Justificativa                   float64
Referência                          str
Situação Partida                    str
Situação Chegada                    str
Codeshare                           str
dtype: object

In [7]:
df.isna().mean().sort_values(ascending=False)

Justificativa                   1.000000
Codeshare                       0.558907
Situação Chegada                0.061295
Situação Partida                0.061295
Partida Real                    0.036154
Chegada Real                    0.036154
Chegada Prevista                0.025141
Partida Prevista                0.025141
Código Tipo Linha               0.000000
Sigla ICAO Empresa Aérea        0.000000
Código DI                       0.000000
Número Voo                      0.000000
Empresa Aérea                   0.000000
Descrição Aeroporto Destino     0.000000
Sigla ICAO Aeroporto Destino    0.000000
Sigla ICAO Aeroporto Origem     0.000000
Descrição Aeroporto Origem      0.000000
Número de Assentos              0.000000
Modelo Equipamento              0.000000
Situação Voo                    0.000000
Referência                      0.000000
dtype: float64

In [8]:
for col in df.columns:
    print(f"\n--- {col} ---")
    print(df[col].head())

--- Sigla ICAO Empresa Aérea ---
0    AAL
1    AAL
2    AAL
3    AAL
4    AAL
Name: Sigla ICAO Empresa Aérea, dtype: str

--- Empresa Aérea ---
0    AMERICAN AIRLINES, INC.
1    AMERICAN AIRLINES, INC.
2    AMERICAN AIRLINES, INC.
3    AMERICAN AIRLINES, INC.
4    AMERICAN AIRLINES, INC.
Name: Empresa Aérea, dtype: str

--- Número Voo ---
0    0904
1    0905
2    0906
3    0925
4    0929
Name: Número Voo, dtype: str

--- Código DI ---
0    0
1    0
2    0
3    0
4    0
Name: Código DI, dtype: str

--- Código Tipo Linha ---
0    I
1    I
2    I
3    I
4    I
Name: Código Tipo Linha, dtype: str

--- Modelo Equipamento ---
0    B788
1    B788
2    B77W
3    B772
4    B77W
Name: Modelo Equipamento, dtype: str

--- Número de Assentos ---
0    295
1    295
2    318
3    288
4    318
Name: Número de Assentos, dtype: int64

--- Sigla ICAO Aeroporto Origem ---
0    SBGL
1    KMIA
2    SBGR
3    KMIA
4    KMIA
Name: Sigla ICAO Aeroporto Origem, dtype: str

--- Descrição Aeroporto Origem ---
0    AEROPORTO INTERNACIONAL DO RIO DE JANEIRO (GAL...
1    MIAMI INTERNATIONAL AIRPORT - MIAMI, FLORIDA -...
2    GUARULHOS - GOVERNADOR ANDRÉ FRANCO MONTORO - ...
3    MIAMI INTERNATIONAL AIRPORT - MIAMI, FLORIDA -...
4    MIAMI INTERNATIONAL AIRPORT - MIAMI, FLORIDA -...
Name: Descrição Aeroporto Origem, dtype: str

--- Partida Prevista ---
0    01/01/2025 23:55
1    01/01/2025 01:10
2    01/01/2025 00:30
3    01/01/2025 23:50
4    01/01/2025 20:50
Name: Partida Prevista, dtype: str

--- Partida Real ---
0    01/01/2025 23:50
1    01/01/2025 01:10
2    01/01/2025 00:20
3    02/01/2025 00:03
4    01/01/2025 22:01
Name: Partida Real, dtype: str

--- Sigla ICAO Aeroporto Destino ---
0    KMIA
1    SBGL
2    KMIA
3    SBGR
4    SBGR
Name: Sigla ICAO Aeroporto Destino, dtype: str

--- Descrição Aeroporto Destino ---
0    MIAMI INTERNATIONAL AIRPORT - MIAMI, FLORIDA -...
1    AEROPORTO INTERNACIONAL DO RIO DE JANEIRO (GAL...
2    MIAMI INTERNATIONAL AIRPORT - MIAMI, FLORIDA -...
3    GUARULHOS - GOVERNADOR ANDRÉ FRANCO MONTORO - ...
4    GUARULHOS - GOVERNADOR ANDRÉ FRANCO MONTORO - ...
Name: Descrição Aeroporto Destino, dtype: str

--- Chegada Prevista ---
0    02/01/2025 07:45
1    01/01/2025 09:25
2    01/01/2025 08:55
3    02/01/2025 08:10
4    02/01/2025 06:20
Name: Chegada Prevista, dtype: str

--- Chegada Real ---
0    02/01/2025 08:11
1    01/01/2025 09:24
2    01/01/2025 08:31
3    02/01/2025 08:37
4    02/01/2025 06:44
Name: Chegada Real, dtype: str

--- Situação Voo ---
0    REALIZADO
1    REALIZADO
2    REALIZADO
3    REALIZADO
4    REALIZADO
Name: Situação Voo, dtype: str

--- Justificativa ---
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: Justificativa, dtype: float64

--- Referência ---
0    01/01/2025 00:00:00
1    01/01/2025 00:00:00
2    01/01/2025 00:00:00
3    01/01/2025 00:00:00
4    01/01/2025 00:00:00
Name: Referência, dtype: str

--- Situação Partida ---
0       Antecipado
1          Pontual
2       Antecipado
3          Pontual
4    Atraso 60-120
Name: Situação Partida, dtype: str

--- Situação Chegada ---
0       Pontual
1    Antecipado
2    Antecipado
3       Pontual
4       Pontual
Name: Situação Chegada, dtype: str

--- Codeshare ---
0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
Name: Codeshare, dtype: str

In [9]:
preprocessor = FlightPreprocessor()
df_processed = preprocessor.transform(df)

In [10]:
df_processed[
    [
        "origin_airport",
        "destination_airport",
        "scheduled_departure",
        "actual_departure",
        "departure_delay_minutes",
    ]
].head(10)

,origin_airport,destination_airport,scheduled_departure,actual_departure,departure_delay_minutes
0,SBGL,KMIA,2025-01-01 23:55:00,2025-01-01 23:50:00,-5.0
1,KMIA,SBGL,2025-01-01 01:10:00,2025-01-01 01:10:00,0.0
2,SBGR,KMIA,2025-01-01 00:30:00,2025-01-01 00:20:00,-10.0
3,KMIA,SBGR,2025-01-01 23:50:00,2025-01-02 00:03:00,13.0
4,KMIA,SBGR,2025-01-01 20:50:00,2025-01-01 22:01:00,71.0
5,SBGR,KMIA,2025-01-01 22:30:00,2025-01-01 22:25:00,-5.0
6,SBGL,KDFW,2025-01-01 23:00:00,2025-01-01 22:38:00,-22.0
7,KDFW,SBGL,2025-01-01 20:00:00,2025-01-01 22:09:00,129.0
8,KMIA,SBGL,2025-01-01 22:10:00,NaT,NaN
9,SBGR,KJFK,2025-01-01 23:15:00,2025-01-01 22:57:00,-18.0

In [11]:
df_processed["departure_delay_minutes"].describe()

count    84123.000000
mean         7.971875
std        164.253599
min       -868.000000
25%         -7.000000
50%         -2.000000
75%          8.000000
max      44635.000000
Name: departure_delay_minutes, dtype: float64

In [12]:
df_processed["flight_status"].value_counts(dropna=False)

flight_status
REALIZADO    86376
CANCELADO     3240
Name: count, dtype: int64

In [13]:
df_processed["departure_delay_minutes"].isna().mean()

np.float64(0.061294858061060525)

In [14]:
df_processed.nlargest(
    10,
    "departure_delay_minutes"
)[
    [
        "origin_airport",
        "destination_airport",
        "scheduled_departure",
        "actual_departure",
        "departure_delay_minutes",
        "flight_status",
    ]
]

,origin_airport,destination_airport,scheduled_departure,actual_departure,departure_delay_minutes,flight_status
612,SNCL,SBSV,2025-01-03 13:45:00,2025-02-03 13:40:00,44635.0,REALIZADO
56489,SBGR,SCEL,2025-01-28 08:10:00,2025-01-30 10:19:00,3009.0,REALIZADO
37530,SBFI,SBGL,2025-01-04 00:05:00,2025-01-05 23:58:00,2873.0,REALIZADO
42383,SBFI,SBGL,2025-01-11 00:05:00,2025-01-12 23:57:00,2872.0,REALIZADO
52075,SBFI,SBGL,2025-01-25 00:05:00,2025-01-26 23:53:00,2868.0,REALIZADO
47246,SBFI,SBGL,2025-01-18 00:05:00,2025-01-19 23:50:00,2865.0,REALIZADO
56372,KMIA,SBEG,2025-01-09 07:55:00,2025-01-10 20:56:00,2221.0,REALIZADO
56373,SBEG,SEQM,2025-01-09 20:55:00,2025-01-11 03:45:00,1850.0,REALIZADO
32417,SBGL,EGLL,2025-01-30 18:10:00,2025-01-31 23:54:00,1784.0,REALIZADO
3020,SBGR,LFPG,2025-01-19 14:40:00,2025-01-20 20:10:00,1770.0,REALIZADO

In [15]:
df_processed.nsmallest(
    10,
    "departure_delay_minutes"
)[
    [
        "origin_airport",
        "destination_airport",
        "scheduled_departure",
        "actual_departure",
        "departure_delay_minutes",
        "flight_status",
    ]
]

,origin_airport,destination_airport,scheduled_departure,actual_departure,departure_delay_minutes,flight_status
56692,LEMD,SBGR,2025-01-30 19:55:00,2025-01-30 05:27:00,-868.0,REALIZADO
57379,SBGL,SABE,2025-01-02 19:15:00,2025-01-02 05:12:00,-843.0,REALIZADO
34404,SBGR,SCEL,2025-01-18 20:40:00,2025-01-18 10:16:00,-624.0,REALIZADO
34403,DNMM,SBGR,2025-01-18 10:40:00,2025-01-18 01:04:00,-576.0,REALIZADO
56463,SBEG,SEQM,2025-01-23 20:55:00,2025-01-23 14:48:00,-367.0,REALIZADO
56507,SBEG,SEQM,2025-01-30 20:55:00,2025-01-30 14:50:00,-365.0,REALIZADO
56417,SBEG,SEQM,2025-01-16 20:55:00,2025-01-16 15:06:00,-349.0,REALIZADO
59762,SBGR,SBEG,2025-01-18 21:05:00,2025-01-18 15:29:00,-336.0,REALIZADO
56326,SBEG,SEQM,2025-01-02 20:55:00,2025-01-02 16:13:00,-282.0,REALIZADO
57185,SBFL,SCEL,2025-01-17 23:00:00,2025-01-17 19:10:00,-230.0,REALIZADO

In [16]:
df_processed["departure_delay_minutes"].quantile(
    [0.001, 0.005, 0.01, 0.05, 0.95, 0.99, 0.995, 0.999]
)

0.001    -58.000
0.005    -24.000
0.010    -19.000
0.050    -14.000
0.950     49.000
0.990    150.780
0.995    224.000
0.999    805.778
Name: departure_delay_minutes, dtype: float64

In [17]:
pd.crosstab(
    df_processed["flight_status"],
    df_processed["departure_delay_minutes"].isna(),
    normalize="index"
)

departure_delay_minutes     False     True
flight_status
CANCELADO                0.000000  1.000000
REALIZADO                0.973916  0.026084

In [18]:
df_processed.groupby("flight_status")[
    "departure_delay_minutes"
].describe()

                 count      mean         std    min  25%  50%  75%      max
flight_status
CANCELADO          0.0       NaN         NaN    NaN  NaN  NaN  NaN      NaN
REALIZADO      84123.0  7.971875  164.253599 -868.0 -7.0 -2.0  8.0  44635.0

In [19]:
airports = pd.read_csv(
    "../data/raw/airports/airports.csv",
    sep=";",
    encoding="latin-1",
    skiprows=1,
)

airports.head()

,Código OACI,CIAD,Nome,Município,UF,Município Servido,UF Servido,LATGEOPOINT,LONGEOPOINT,Latitude,Longitude,Altitude,Operação Diurna,Operação Noturna,Situação,Validade do Registro,Portaria de Registro,Link Portaria
0,SBRB,AC0001,Plácido de Castro,RIO BRANCO,Acre,Rio Branco,Acre,-9.868333,-67.898056,"09°52'06""S","067°53'53""W","193,0",VFR / IFR - CAT I,VFR / IFR - CAT I,Cadastrado,NaN,NaN,NaN
1,SWPI,AM0006,Parintins,PARINTINS,Amazonas,Parintins,Amazonas,-2.673611,-56.777500,"02°40'25""S","056°46'39""W","25,0",VFR,VFR,Cadastrado,NaN,NaN,NaN
2,SBMQ,AP0001,Alberto Alcolumbre,MACAPÁ,Amapá,Macapá,Amapá,0.050556,-51.072222,"00°03'02""N","051°04'20""W","17,0",VFR / IFR Não Precisão,VFR / IFR Não Precisão,Cadastrado,NaN,NaN,NaN
3,SBVC,BA0005,Glauber de Andrade Rocha,VITÓRIA DA CONQUISTA,Bahia,Vitória da Conquista,Bahia,-14.907778,-40.914722,"14°54'28""S","040°54'53""W","894,0",VFR / IFR Não Precisão,VFR / IFR Não Precisão,Cadastrado,26/12/2027,PA2019-2438,https://pergamum.anac.gov.br/arquivos/PA2019-2...
4,SBLE,BA0006,HORÁCIO DE MATTOS,LENÇÓIS,Bahia,Lençóis,Bahia,-12.482222,-41.276944,"12°28'56""S","041°16'37""W","506,0",VFR,VFR,Cadastrado,NaN,NaN,NaN

In [20]:
airports.columns.tolist()

['Código OACI',
 'CIAD',
 'Nome',
 'Município',
 'UF',
 'Município Servido',
 'UF Servido',
 'LATGEOPOINT',
 'LONGEOPOINT',
 'Latitude',
 'Longitude',
 'Altitude',
 'Operação Diurna',
 'Operação Noturna',
 'Situação',
 'Validade do Registro',
 'Portaria de Registro',
 'Link Portaria']

In [21]:
airports = airports[
    [
        "Código OACI",
        "Nome",
        "Município",
        "UF",
        "LATGEOPOINT",
        "LONGEOPOINT",
    ]
].copy()

In [25]:
airports

,Código OACI,Nome,Município,UF,LATGEOPOINT,LONGEOPOINT
0,SBRB,Plácido de Castro,RIO BRANCO,Acre,-9.868333,-67.898056
1,SWPI,Parintins,PARINTINS,Amazonas,-2.673611,-56.777500
2,SBMQ,Alberto Alcolumbre,MACAPÁ,Amapá,0.050556,-51.072222
3,SBVC,Glauber de Andrade Rocha,VITÓRIA DA CONQUISTA,Bahia,-14.907778,-40.914722
4,SBLE,HORÁCIO DE MATTOS,LENÇÓIS,Bahia,-12.482222,-41.276944
...,...,...,...,...,...,...
491,SDAE,São Pedro,SÃO PEDRO,São Paulo,-22.583611,-47.896111
492,SNIU,Ipiaú,IPIAÚ,Bahia,-14.173333,-39.684167
493,SDAG,Angra Dos Reis,ANGRA DOS REIS,Rio de Janeiro,-22.975278,-44.307222
494,SWBR,Borba,BORBA,Amazonas,-4.406111,-59.602500
495,SNMA,Monte Alegre,MONTE ALEGRE,Pará,-1.996667,-54.071389

In [26]:
airports[airports["Código OACI"] == "SBGR"]

,Código OACI,Nome,Município,UF,LATGEOPOINT,LONGEOPOINT
121,SBGR,Guarulhos - Governador André Franco Montoro,GUARULHOS,São Paulo,-23.435556,-46.473056

In [27]:
airports = airports.rename(
    columns={
        "Código OACI": "airport_icao",
        "Nome": "airport_name",
        "Município": "city",
        "UF": "state",
        "LATGEOPOINT": "latitude",
        "LONGEOPOINT": "longitude",
    }
)

In [28]:
df_brazil = df_processed.merge(
    airports,
    left_on="origin_airport",
    right_on="airport_icao",
    how="inner",
)

In [29]:
df_brazil[
    [
        "origin_airport",
        "destination_airport",
        "scheduled_departure",
        "departure_delay_minutes",
        "city",
        "state",
        "latitude",
        "longitude",
    ]
].head(10)

,origin_airport,destination_airport,scheduled_departure,departure_delay_minutes,city,state,latitude,longitude
0,SBGL,KMIA,2025-01-01 23:55:00,-5.0,RIO DE JANEIRO,Rio de Janeiro,-22.810000,-43.250556
1,SBGR,KMIA,2025-01-01 00:30:00,-10.0,GUARULHOS,São Paulo,-23.435556,-46.473056
2,SBGR,KMIA,2025-01-01 22:30:00,-5.0,GUARULHOS,São Paulo,-23.435556,-46.473056
3,SBGL,KDFW,2025-01-01 23:00:00,-22.0,RIO DE JANEIRO,Rio de Janeiro,-22.810000,-43.250556
4,SBGR,KJFK,2025-01-01 23:15:00,-18.0,GUARULHOS,São Paulo,-23.435556,-46.473056
5,SBGR,KMIA,2025-01-01 23:50:00,NaN,GUARULHOS,São Paulo,-23.435556,-46.473056
6,SBGR,KDFW,2025-01-01 23:00:00,11.0,GUARULHOS,São Paulo,-23.435556,-46.473056
7,SBGL,KMIA,2025-01-01 22:15:00,6.0,RIO DE JANEIRO,Rio de Janeiro,-22.810000,-43.250556
8,SBGL,KJFK,2025-01-01 23:00:00,-3.0,RIO DE JANEIRO,Rio de Janeiro,-22.810000,-43.250556
9,SBGL,KMIA,2025-01-02 23:55:00,-3.0,RIO DE JANEIRO,Rio de Janeiro,-22.810000,-43.250556

In [30]:
print(f"Antes: {len(df_processed):,}")
print(f"Depois: {len(df_brazil):,}")
print(f"Aeroportos brasileiros: {df_brazil['origin_airport'].nunique()}")

Antes: 89,616
Depois: 80,444
Aeroportos brasileiros: 153

In [31]:
airport_origins = (
    df_brazil[
        [
            "origin_airport",
            "airport_name",
            "city",
            "state",
            "latitude",
            "longitude",
        ]
    ]
    .drop_duplicates()
    .sort_values("origin_airport")
    .reset_index(drop=True)
)

airport_origins.head()

,origin_airport,airport_name,city,state,latitude,longitude
0,SBAE,Bauru/Arealva,BAURU,São Paulo,-22.157778,-49.068333
1,SBAQ,Bartolomeu de Gusmão,ARARAQUARA,São Paulo,-21.811944,-48.133056
2,SBAR,Santa Maria,ARACAJU,Sergipe,-10.985278,-37.073333
3,SBAT,PILOTO OSVALDO MARQUES DIAS,ALTA FLORESTA,Mato Grosso,-9.866389,-56.105000
4,SBAU,Araçatuba,ARAÇATUBA,São Paulo,-21.144167,-50.426389

In [32]:
airport_origins.shape

(153, 6)

In [33]:
airport_origins[
    ["latitude", "longitude"]
].isna().sum()

latitude     0
longitude    0
dtype: int64

In [34]:
df_brazil["origin_airport"].value_counts().head(20)

origin_airport
SBGR    12590
SBSP     8204
SBKP     5562
SBCF     5152
SBGL     5080
SBBR     4674
SBRF     3826
SBSV     2814
SBRJ     2488
SBCT     2235
SBFL     2072
SBPA     2003
SBFZ     1981
SBBE     1453
SBEG     1423
SBGO     1181
SBVT     1127
SBMO     1100
SBPS     1019
SBCY      909
Name: count, dtype: int64

In [40]:
loader = FlightLoader(
    input_dir="../data/raw/flights"
)

df_all = loader.load_all()

Loading: ..\data\raw\flights\2022\VRA_2022_01.csv
Loading: ..\data\raw\flights\2022\VRA_2022_02.csv
Loading: ..\data\raw\flights\2022\VRA_2022_03.csv
Loading: ..\data\raw\flights\2022\VRA_2022_04.csv

C:\Users\Adam\Documents\Repositorio\RainDelay\src\rain_delay\data\flight_loader.py:23: DtypeWarning: Columns (0: Número Voo, 1: Código DI) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

Loading: ..\data\raw\flights\2022\VRA_2022_05.csv
Loading: ..\data\raw\flights\2022\VRA_2022_06.csv
Loading: ..\data\raw\flights\2022\VRA_2022_07.csv
Loading: ..\data\raw\flights\2022\VRA_2022_08.csv
Loading: ..\data\raw\flights\2022\VRA_2022_09.csv
Loading: ..\data\raw\flights\2022\VRA_2022_10.csv
Loading: ..\data\raw\flights\2022\VRA_2022_11.csv
Loading: ..\data\raw\flights\2022\VRA_2022_12.csv
Loading: ..\data\raw\flights\2023\VRA_2023_01.csv
Loading: ..\data\raw\flights\2023\VRA_2023_02.csv
Loading: ..\data\raw\flights\2023\VRA_2023_03.csv
Loading: ..\data\raw\flights\2023\VRA_2023_04.csv
Loading: ..\data\raw\flights\2023\VRA_2023_05.csv
Loading: ..\data\raw\flights\2023\VRA_2023_06.csv
Loading: ..\data\raw\flights\2023\VRA_2023_07.csv
Loading: ..\data\raw\flights\2023\VRA_2023_08.csv
Loading: ..\data\raw\flights\2023\VRA_2023_09.csv
Loading: ..\data\raw\flights\2023\VRA_2023_10.csv
Loading: ..\data\raw\flights\2023\VRA_2023_11.csv
Loading: ..\data\raw\flights\2023\VRA_2023_12.csv
Loading: ..\data\raw\flights\2024\VRA_2024_01.csv
Loading: ..\data\raw\flights\2024\VRA_2024_02.csv
Loading: ..\data\raw\flights\2024\VRA_2024_03.csv
Loading: ..\data\raw\flights\2024\VRA_2024_04.csv
Loading: ..\data\raw\flights\2024\VRA_2024_05.csv
Loading: ..\data\raw\flights\2024\VRA_2024_06.csv
Loading: ..\data\raw\flights\2024\VRA_2024_07.csv
Loading: ..\data\raw\flights\2024\VRA_2024_08.csv
Loading: ..\data\raw\flights\2024\VRA_2024_09.csv
Loading: ..\data\raw\flights\2024\VRA_2024_10.csv
Loading: ..\data\raw\flights\2024\VRA_2024_11.csv
Loading: ..\data\raw\flights\2024\VRA_2024_12.csv
Loading: ..\data\raw\flights\2025\VRA_2025_01.csv
Loading: ..\data\raw\flights\2025\VRA_2025_02.csv
Loading: ..\data\raw\flights\2025\VRA_2025_03.csv
Loading: ..\data\raw\flights\2025\VRA_2025_04.csv
Loading: ..\data\raw\flights\2025\VRA_2025_05.csv
Loading: ..\data\raw\flights\2025\VRA_2025_06.csv
Loading: ..\data\raw\flights\2025\VRA_2025_07.csv
Loading: ..\data\raw\flights\2025\VRA_2025_08.csv
Loading: ..\data\raw\flights\2025\VRA_2025_09.csv
Loading: ..\data\raw\flights\2025\VRA_2025_10.csv
Loading: ..\data\raw\flights\2025\VRA_2025_11.csv
Loading: ..\data\raw\flights\2025\VRA_2025_12.csv

In [42]:
df_all.shape

(3849691, 21)

In [43]:
df_all.columns.tolist()

['Sigla ICAO Empresa Aérea',
 'Empresa Aérea',
 'Número Voo',
 'Código DI',
 'Código Tipo Linha',
 'Modelo Equipamento',
 'Número de Assentos',
 'Sigla ICAO Aeroporto Origem',
 'Descrição Aeroporto Origem',
 'Partida Prevista',
 'Partida Real',
 'Sigla ICAO Aeroporto Destino',
 'Descrição Aeroporto Destino',
 'Chegada Prevista',
 'Chegada Real',
 'Situação Voo',
 'Justificativa',
 'Referência',
 'Situação Partida',
 'Situação Chegada',
 'Codeshare']

In [44]:
preprocessor = FlightPreprocessor()

df_all_processed = preprocessor.transform(df_all)

In [45]:
df_all_processed[
    [
        "origin_airport",
        "destination_airport",
        "scheduled_departure",
        "actual_departure",
        "departure_delay_minutes",
    ]
].head()

,origin_airport,destination_airport,scheduled_departure,actual_departure,departure_delay_minutes
0,SBGL,KMIA,2022-01-01 00:05:00,2021-12-31 23:50:00,-15.0
1,KMIA,SBGL,2022-01-01 22:00:00,2022-01-01 23:19:00,79.0
2,SBGR,KMIA,2022-01-01 00:05:00,2022-01-01 00:06:00,1.0
3,KMIA,SBGR,2022-01-01 22:00:00,2022-01-01 21:53:00,-7.0
4,SBGR,KMIA,2022-01-01 22:30:00,2022-01-01 22:30:00,0.0

In [46]:
df_all_processed.shape

(3849691, 23)

In [47]:
df_all_brazil = df_all_processed.merge(
    airports,
    left_on="origin_airport",
    right_on="airport_icao",
    how="inner",
)

In [48]:
print(f"Antes: {len(df_all_processed):,}")
print(f"Depois: {len(df_all_brazil):,}")
print(
    "Aeroportos brasileiros:",
    df_all_brazil["origin_airport"].nunique()
)

Antes: 3,849,691
Depois: 3,505,891
Aeroportos brasileiros: 211

In [49]:
airport_origins = (
    df_all_brazil[
        [
            "origin_airport",
            "airport_name",
            "city",
            "state",
            "latitude",
            "longitude",
        ]
    ]
    .drop_duplicates()
    .sort_values("origin_airport")
    .reset_index(drop=True)
)

In [50]:
airport_origins.shape

(211, 6)

In [51]:
airport_origins[["latitude", "longitude"]].isna().sum()

latitude     0
longitude    0
dtype: int64

In [53]:
builder = DatasetBuilder(output_dir="../data/processed")

df_flights_final = builder.build_flights(
    flights=df_all_processed,
    airports=airports,
)

df_airports_final = builder.build_airports(
    flights_brazil=df_flights_final,
)

In [54]:
df_flights_final.shape

(3505891, 29)

In [55]:
df_airports_final.shape

(211, 6)

In [58]:
df_flights_final["flight_number"] = (
    df_flights_final["flight_number"]
    .astype("string")
)

In [59]:
df_flights_final["flight_number"].dtype

In [61]:
df_flights_final.select_dtypes(include="object").columns.tolist()

C:\Users\Adam\AppData\Local\Temp\ipykernel_18832\3323083897.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df_flights_final.select_dtypes(include="object").columns.tolist()

['airline_icao',
 'airline',
 'Código DI',
 'Código Tipo Linha',
 'aircraft_model',
 'origin_airport',
 'origin_airport_name',
 'destination_airport',
 'destination_airport_name',
 'flight_status',
 'Referência',
 'Situação Partida',
 'Situação Chegada',
 'Codeshare',
 'airport_icao',
 'airport_name',
 'city',
 'state']

In [63]:
df_flights_final["Código DI"] = (
    df_flights_final["Código DI"]
    .astype("string")
)

In [64]:
builder.save(
    flights=df_flights_final,
    airports=df_airports_final,
)

In [66]:
df_flights_final["flight_number"] = (
    df_flights_final["flight_number"].astype("string")
)

df_flights_final["Código DI"] = (
    df_flights_final["Código DI"].astype("string")
)